apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongo.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "common.name" . }}
    env: {{ .Values.env }}
type: Opaque
data:
  {{ .Values.secrets.mongo.usernameKey }}: {{ .Values.secrets.mongo.username | b64enc }}
  {{ .Values.secrets.mongo.passwordKey }}: {{ .Values.secrets.mongo.password | b64enc }}
